target_schema:
  columns:
    - name: "target_col_1"
      source: "source_col_1"
      type: "string"
    - name: "target_col_2"
      source: "source_col_2"
      type: "integer"
    - name: "target_col_3"
      source: "source_col_3"
      type: "date"
      format: "yyyy-MM-dd"
