-- Create a new user
CREATE USER joyboy IDENTIFIED BY password;

-- Grant privileges to the user
GRANT CONNECT, RESOURCE, DBA TO joyboy;

-- Switch to the new user
ALTER SESSION SET CURRENT_SCHEMA = joyboy;

-- Create a users table
CREATE TABLE users (user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,first_name VARCHAR2(50),last_name VARCHAR2(50),email VARCHAR2(100),created_at DATE DEFAULT SYSDATE,PRIMARY KEY (user_id));

-- Insert some sample data into the users table
INSERT INTO users (first_name, last_name, email) VALUES ('Monkey', 'D. Luffy', 'luffy@onepiece.com');
INSERT INTO users (first_name, last_name, email) VALUES ('Roronoa', 'Zoro', 'zoro@onepiece.com');
INSERT INTO users (first_name, last_name, email) VALUES ('Nami', 'Cat Burglar', 'nami@onepiece.com');

-- Commit the transaction
COMMIT;

-- Verify the inserted data
SELECT * FROM users;
